version: "3.9"
services:
  db:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      HOST: 127.0.0.1
      MYSQL_DATABASE: "snippetbox"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - "./.mysql-data/db:/var/lib/mysql"
    networks:
      - my-network

  app:
    build:
      dockerfile: Dockerfile
      context: .
      target: dev
    environment:
      HOST: 127.0.0.1
    ports:
      - "4000:4000"
    expose:
      - "4000"
    volumes:
      - ./:/app/
    depends_on:
      - db
    networks:
      - my-network

networks:
  my-network:
    driver: bridge