version: "3.3"
services:
  db:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      HOST: 0.0.0.0
      MYSQL_DATABASE: "snippetbox"
      MYSQL_USER: "web"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - "./.mysql-data/db:/var/lib/mysql"
